name       : protonvpn-cli
version    : 1.1.2
release    : 2
source     :
    -  https://github.com/ProtonVPN/protonvpn-cli/archive/v1.1.2.tar.gz : d58b2a9acca5eb0c81c07ba7021d40bb3230f871ec9537b5546cbe0268bb0d7f
license    : MIT
component  : network.clients
summary    : ProtonVPN CLI tool for protonvpn.com
description: |
    ProtonVPN CLI tool for protonvpn.com
rundeps    :
    - dialog
    - openvpn
    - procps-ng
    - python3
install    : |
    install -Dm00755 ./protonvpn-cli.sh "$installdir/usr/bin/protonvpn-cli"
    ln -s -f "/usr/bin/protonvpn-cli" "$installdir/usr/bin/pvpn"
    install -Dm00644 ./license.md "$installdir/usr/share/doc/protonvpn-cli/LICENSE"
