name       : protonvpn-cli
version    : 3.13.0
release    : 16
source     :
    - https://github.com/ProtonVPN/linux-cli/archive/refs/tags/3.13.0.tar.gz : d295d6c899638a88d615e2cacb078ecf2aee8c771ebb087c9edb43aea25aacd9
license    : GPL-3.0-or-later
component  : network.clients
summary    : ProtonVPN CLI tool for protonvpn.com
description: |
    ProtonVPN CLI tool for protonvpn.com
builddeps  :
    - python-dbus
    - pyxdg
    - python-pythondialog
rundeps    :
    # `proton-python-client` will be installed by `protonvpn-nm-lib`.
    - protonvpn-nm-lib
    - python-pythondialog
build      : |
    %python3_setup
install    : |
    %python3_install
