name       : protonvpn-cli
version    : 3.12.0
release    : 15
source     :
    - https://github.com/ProtonVPN/linux-cli/archive/refs/tags/3.11.1.tar.gz : 6abc3d28a9506d0654f68447e222d038b44313ee4120cc3fa936ff4c02128641
license    : GPL-3.0-or-later
component  : network.clients
summary    : ProtonVPN CLI tool for protonvpn.com
description: |
    ProtonVPN CLI tool for protonvpn.com
builddeps  :
    - python-dbus
    - pyxdg
    - python-pythondialog
rundeps    :
    # `proton-python-client` will be installed by `protonvpn-nm-lib`.
    - protonvpn-nm-lib
    - python-pythondialog
build      : |
    %python3_setup
install    : |
    %python3_install
