name       : protonvpn-cli
version    : 3.10.0
release    : 11
source     :
    - https://github.com/ProtonVPN/linux-cli/archive/refs/tags/3.10.0.tar.gz : 617d9738ec4ab42c80de95bf6dcf205735a07b22c2d7659d2d689a03ea763b8a
    - https://github.com/ProtonMail/proton-python-client/archive/refs/tags/0.7.0.tar.gz : 34c075b4c481f10f500c71ac7a113ba57dc0368d874042e7fc0840c5c5754e26
    - https://github.com/ProtonVPN/protonvpn-nm-lib/archive/refs/tags/3.5.0.tar.gz : 05629d36b9d46b34df2624bc4c7fdc74fcf2041ed19aa5a1c589778d6733800b
license    : GPL-3.0-or-later
component  : network.clients
summary    : ProtonVPN CLI tool for protonvpn.com
description: |
    ProtonVPN CLI tool for protonvpn.com
builddeps  :
    - pkgconfig(pygobject-3.0)
    - gnome-keyring
    - networkmanager-openvpn
    - python-bcrypt
    - python-distro
    - python-gnupg
    - python-jinja
    - python-keyring
    - python-openssl
    - python-pythondialog
    - python-requests
    - pyxdg
rundeps    :
    - gnome-keyring
    - networkmanager-openvpn
    - python-bcrypt
    - python-distro
    - python-gnupg
    - python-jinja
    - python-keyring
    - python-openssl
    - python-pythondialog
    - python-requests
    - pyxdg
setup      : |
    tar -xf $sources/0.7.0.tar.gz -C .
    tar -xf $sources/3.5.0.tar.gz -C .
    
    cd proton-python-client-0.7.0
    python3 setup.py build # If we use macro, the package won't be installed correctly
    python3 setup.py install --root=$installdir --optimize=1

    cd ../protonvpn-nm-lib-3.5.0
    python3 setup.py build
    python3 setup.py install --root=$installdir --optimize=1
build      : |
    %python3_setup
install    : |
    %python3_install
