name       : protonvpn-cli
version    : 1.1.0
release    : 1
source     :
    -  https://github.com/ProtonVPN/protonvpn-cli/archive/v1.1.0.tar.gz : 1a8eb6b2ab8bc6327eca920ad86b452aeff9470d3205e3fe4dfcc7a799937811
license    : MIT
component  : network.clients
summary    : ProtonVPN CLI tool for protonvpn.com
description: |
    ProtonVPN CLI tool for protonvpn.com
rundeps    :
    - dialog
    - openvpn
    - procps-ng
    - python3
install    : |
    install -Dm755 ./protonvpn-cli.sh "$installdir/usr/bin/protonvpn-cli"
    ln -s -f "/usr/bin/protonvpn-cli" "$installdir/usr/bin/pvpn"
    install -Dm644 ./license.md "$installdir/usr/share/doc/protonvpn-cli/LICENSE"

