name       : protonvpn-cli
version    : 2.2.4
release    : 5
source     :
    - https://github.com/ProtonVPN/linux-cli/archive/v2.2.4.tar.gz : d7deff214118ba0b38a6eac697f8148f99b1e50e1404021b45f9f4749ea81fe8
license    : GPL-3.0-or-later
component  : network.clients
summary    : ProtonVPN CLI tool for protonvpn.com
description: |
    ProtonVPN CLI tool for protonvpn.com
rundeps    :
    - dialog
    - openvpn
    - procps-ng
    - python-docopt
    - python-jinja
    - python-pythondialog
    - python-requests
install    : |
    %python3_install
