name       : protonvpn-cli
version    : 3.8.0
release    : 10
source     :
    - https://github.com/ProtonVPN/linux-cli/archive/refs/tags/3.8.0.tar.gz : 3200a64bee0e085dec61dda208b00df7eeb8b3e7f69fc62234372faaf8459214
    - https://github.com/ProtonMail/proton-python-client/archive/refs/tags/0.5.1.tar.gz : 941cd8bc41a9e976c98d40f64474c7f8c9070958118c659cfd5b41c7e1a80332
    - https://github.com/ProtonVPN/protonvpn-nm-lib/archive/refs/tags/3.3.2.tar.gz : 353571f9cb1beeafcb685ead2e3240a1defc3ad4b3ea9309ffea393e20bab7ee
license    : GPL-3.0-or-later
component  : network.clients
summary    : ProtonVPN CLI tool for protonvpn.com
description: |
    ProtonVPN CLI tool for protonvpn.com
builddeps  :
    - pkgconfig(pygobject-3.0)
    - gnome-keyring
    - networkmanager-openvpn
    - python-bcrypt
    - python-distro
    - python-gnupg
    - python-jinja
    - python-keyring
    - python-openssl
    - python-pythondialog
    - python-requests
    - pyxdg
rundeps    :
    - gnome-keyring
    - networkmanager-openvpn
    - python-bcrypt
    - python-distro
    - python-gnupg
    - python-jinja
    - python-keyring
    - python-openssl
    - python-pythondialog
    - python-requests
    - pyxdg
setup      : |
    tar -xf $sources/0.5.1.tar.gz -C .
    tar -xf $sources/3.3.2.tar.gz -C .
    
    cd proton-python-client-0.5.1
    python3 setup.py build # If we use macro, the package won't be installed correctly
    python3 setup.py install --root=$installdir --optimize=1

    cd ../protonvpn-nm-lib-3.3.2
    python3 setup.py build
    python3 setup.py install --root=$installdir --optimize=1
build      : |
    %python3_setup
install    : |
    %python3_install
