name       : protonvpn-cli
version    : 2.2.11
release    : 9
source     :
    - https://github.com/ProtonVPN/linux-cli-community/archive/refs/tags/v2.2.11.tar.gz : 2fc643762e9156928b706c31a7826427a7ca12c7ae4cdfb656746cd2de3af66b
license    : GPL-3.0-or-later
component  : network.clients
summary    : ProtonVPN CLI tool for protonvpn.com
description: |
    ProtonVPN CLI tool for protonvpn.com
rundeps    :
    - dialog
    - openvpn
    - procps-ng
    - python-distro
    - python-docopt
    - python-jinja
    - python-pythondialog
    - python-requests
install    : |
    %python3_install
