name       : protonvpn-cli
version    : 3.11.0
release    : 12
source     :
    - https://github.com/ProtonVPN/linux-cli/archive/refs/tags/3.11.0.tar.gz : b2cc9196cc3bcb6e29326bde72c8230f04f6d51e6aea4fbf221cc4064361d972
license    : GPL-3.0-or-later
component  : network.clients
summary    : ProtonVPN CLI tool for protonvpn.com
description: |
    ProtonVPN CLI tool for protonvpn.com
builddeps  :
    - python-dbus
    - pyxdg
    - python-pythondialog
rundeps    :
    # `proton-python-client` will be installed by `protonvpn-nm-lib`.
    - protonvpn-nm-lib
    - python-pythondialog
build      : |
    %python3_setup
install    : |
    %python3_install
